### ISSUE TITLE
Error from most taskbar menus when Linked window is closed.

### ISSUE THREAD

**Issue by Gazook89** [lostdesign/linked#96]
**Describe the bug**
On MacOS, if the Linked window is closed but the program is still running, many of the options in the MacOS taskbar return a js error.

**To Reproduce**
1. Close the main calendar window, keeping Linked open.
2. In the MacOS taskbar, choose any option from the "View" menu, or "Settings" from the File menu.
3. Get error:

```
Uncaught Exception:
TypeError: Cannot read property 'webContents' of null
at click (/Applications/linked.app/Contents/Resources/app.asar/background.js:2:556000)
at MenuItem.click (electron/js2c/browser_init.js:73:1742)
at Object.a._executeCommand (electron/js2c/browser_init.js:81:2492)
```

**Expected behavior**
 Should re-open the main calendar window and go to the appropriate location ("today", "settings", etc)

**Desktop (please complete the following information):**
 - Version 1.3.5 (1.3.5)
 - MacOS Big Sur 11.6

**Additional Note**
There should also be an option in "File" menu to open a calendar window.  And further, and more a "feature request", but ability to have multiple calendar windows open (either windowed or tabs).

**Comment by lostdesign** [comment]
In case you are wondering, I thought about adding issuehunt to this project, but it turns out that issuehunt is not actively maintained anymore. So I kinda fear anyone putting money into this, will probably loose it. I'll do more research to add something else or wait for a response of the owners of that project to re-activate it.
